create database ecommerce;

use ecommerce;

CREATE TABLE produto(
SKU VARCHAR(255)PRIMARY KEY ,
NOME VARCHAR (150) NOT NULL,
PRECO_VENDA BIGINT,
QUANTIDADE_ESTOQUE INT,
STATUS VARCHAR (10) CHECK (STATUS IN ('ATIVO','INATIVO'))
);

ALTER TABLE PRODUTO MODIFY PRECO_VENDA DECIMAL (10,2);

SELECT * FROM PRODUTO;

INSERT INTO produto (SKU, NOME, PRECO_VENDA, QUANTIDADE_ESTOQUE, STATUS) VALUES
('NOTE-DELL-I15', 'Notebook Dell Inspiron 15', 3500.00, 15, 'ATIVO'),
('MOUSE-LOGI-M280', 'Mouse Sem Fio Logitech M280', 79.90, 50, 'ATIVO'),
('KB-KEYC-K2', 'Teclado Mecânico Sem Fio Keychron K2', 649.00, 8, 'ATIVO'),
('MON-LG-29WK', 'Monitor LG 29 Ultrawide IPS', 1299.90, 12, 'ATIVO'),
('HEAD-SONY-XM4', 'Fone de Ouvido Bluetooth Sony WH-1000XM4', 1999.00, 0, 'INATIVO'),
('CAM-RED-FHD', 'Webcam Full HD Redragon Hitman', 249.90, 25, 'ATIVO'),
('SSD-KING-480', 'SSD Kingston A400 480GB SATA', 189.00, 100, 'ATIVO'),
('CHAIR-DT3-GT', 'Cadeira Gamer DT3 Sports GT', 1150.00, 5, 'ATIVO');

SELECT * FROM PRODUTO WHERE PRECO_VENDA > 500;

SELECT * FROM PRODUTO WHERE PRECO_VENDA < 500;

UPDATE produto
SET QUANTIDADE_ESTOQUE = 10,
    STATUS = 'ATIVO'
WHERE SKU = 'HEAD-SONY-XM4';

